server:
  port: 8888
spring:
  application:
    name: demoConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JJUNNAK/demo-config-server
          default-label: main
          search-paths: demo-config-server/demo-config-files/**